/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Demux2
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel,
    input in
);
    assign out_0 = (sel == 2'h0)? in : Default;
    assign out_1 = (sel == 2'h1)? in : Default;
    assign out_2 = (sel == 2'h2)? in : Default;
    assign out_3 = (sel == 2'h3)? in : Default;
endmodule


module CU (
  input [31:0] Instruction,
  output [8:0] Opcode,
  output [4:0] Rd,
  output [4:0] Rs1,
  output [4:0] Rs2,
  output [1:0] ST, // Shift Type
                   // 00: Logical Shift Left (LSL)
                   // 01: Logical Shift Right (LSR)
                   // 10: Arithmetic Shift Right (ASR)
                   // 11: Reserved
  output [5:0] SA, // Shift Amount
  output FS, // Freeze Status
  output [12:0] Rs1ImmVal, // Freeze Status
  output [17:0] Offset,
  output [12:0] Rs2ImmVal, // Freeze Status
  output [4:0] Rs1A,
  output [4:0] Rs2B,
  output ImmRs2, // Is Rs1 immediate?
  output ImmRs1, // Is Rs2 immediate?
  output [4:0] operation, // Is Rs2 immediate?
  output ALUMath,
  output Branch,
  output Load,
  output Store,
  output JMPR // Register-based jump

);
  wire [17:0] Offset_temp;
  wire [8:0] Opcode_temp;
  wire [4:0] operation_temp;
  wire [1:0] s0;
  wire s1;
  wire s2;
  assign Offset_temp = Instruction[17:0];
  assign Rd = Instruction[22:18];
  assign Opcode_temp = Instruction[31:23];
  assign SA[4:0] = Offset_temp[5:1];
  assign SA[5] = 1'b0;
  assign Rs2B = Offset_temp[4:0];
  assign Rs1ImmVal = Offset_temp[17:5];
  assign Rs2ImmVal = Offset_temp[12:0];
  assign Rs1A = Offset_temp[17:13];
  assign FS = Offset_temp[0];
  assign ST = Offset_temp[7:6];
  assign Rs2 = Offset_temp[12:8];
  assign Rs1 = Offset_temp[17:13];
  assign ImmRs2 = Opcode_temp[0];
  assign ImmRs1 = Opcode_temp[1];
  assign operation_temp = Opcode_temp[6:2];
  assign s0 = Opcode_temp[8:7];
  Demux2 #(
    .Default(0)
  )
  Demux2_i0 (
    .sel( s0 ),
    .in( 1'b1 ),
    .out_0( ALUMath ),
    .out_1( Branch ),
    .out_2( s1 )
  );
  assign s2 = operation_temp[4];
  assign Load = (s1 & s2);
  assign Store = (s1 & ~ s2);
  assign JMPR = (s1 & s2);
  assign Opcode = Opcode_temp;
  assign Offset = Offset_temp;
  assign operation = operation_temp;
endmodule
