; ==============================================================================
; SAM32 ASSEMBLER STRESS TEST & EDGE CASES
; ==============================================================================
; GENERATED BY GPT

; 1. DIRECTIVES & CONSTANTS 
; Tests: .equ, inline EQU, and lexer number parsing (hex, binary, negative)
.equ HEX_CONST, 0xDEAD
BIN_CONST EQU 0b10101010
NEG_CONST EQU -4096

; 2. TEXT SEGMENT START 
; Tests: .org directive and absolute addressing base
.text
.org 0x00000000

start:
    ; --- LEXER EDGE CASES ---
    ; Tests: Case insensitivity, spacing, zero-register alias (zr), and .F suffix
    add r1, r2, r3
    SUB.F R4, R5, R6, LSL #8     ; Freeze flag (.F) + barrel shifter
    xor zr, r1, r2               ; 'zr' alias + flag updating (TEQ equivalent)

    ; Tests: Number literal bounds (13-bit signed limits)
    add r7, r0, #0b11110000      ; Binary immediate
    add r8, r0, #-0xFF           ; Negative hex
    add r9, r0, #-4096           ; Min 13-bit signed bound (Should NOT throw error)
    add r10, r0, #4095           ; Max 13-bit signed bound (Should NOT throw error)
    ; add r11, r0, #4096         ; Uncomment to test bounds-checking error!

    ; --- COMMUTATIVE IMMEDIATE TOGGLES ---
    ; I-Type A (Standard Immediate replacing Rs2)
    add r11, r1, #100
    
    ; I-Type B (Immediate replaces Rs1)
    ; Tests: Imm Rs1 toggle bit (23) and the weird [17:5] bit-packing layout
    sub r12, #200, r2            
    
    ; NEG pseudo-op (Expands to I-Type B: SUB Rd, #0, Rs)
    neg r13, r5

    ; --- SHIFTS & LOGICAL ---
    ; Pseudo-ops utilizing the barrel shifter and R0 (zr)
    lsl r14, r1, #16             ; Expands to ADD R14, R0, R1, LSL #16
    asr r15, r2, #4              ; Expands to ADD R15, R0, R2, ASR #4
    
    ; Native R-Type shift
    or r16, r3, r4, LSR #2

    ; --- CONTROL FLOW & PC-RELATIVE MATH ---
    cmp r1, r2                   ; Expands to SUB R0, R1, R2
    beq r0, target_a             ; Forward PC-relative branch
    
    call my_func                 ; Expands to B LR, my_func (Jumps over data)
    jmp skip_data                  ; Unconditional jump (Expands to B R0, skip_data)

target_a:
    inc r1                       ; Expands to ADD R1, R1, #1

skip_data:

; ==============================================================================
; 3. INTERLEAVED DATA SEGMENT 
; Tests: Segment switching. The assembler MUST calculate data_segment.addr_base 
; based on the FINAL text_segment.cursor, even if we switch back and forth.
; ==============================================================================
.data
my_array:
    .word 10, 20, 30             ; 12 bytes
    .half 0x1234, -1             ; 4 bytes
    .byte 0xFF, 0x00             ; 2 bytes
    .string "Edge\n\t\\\""       ; 9 bytes + null terminator (10 bytes). Tests escapes.
    .space 16                    ; 16 bytes of padding

; Return to Text Segment
.text

; ==============================================================================
; 4. MEMORY ACCESS & LABEL RESOLUTION
; ==============================================================================
    ; LI pseudo-op loading a 32-bit label address
    ; Tests: Multi-instruction expansion and dynamic addr_offset recalculation
    li r20, my_array             
    
    ; Load from memory (Tests 13-bit signed memory offset)
    lw r21, r20, #0              ; Load first word (10)
    lw r22, r20, #12             ; Load halfword (offset by 3 words)
    
    ; Store to memory (Tests SW encoding where Rd acts as Source)
    sw r21, r20, #28             ; Store into .space area (Offset: 12+4+2+10 = 28)

; ==============================================================================
; 5. STACK OPERATIONS & INDIRECT BRANCHES
; ==============================================================================
    ; Stack operations (using sp / r31 aliases)
    push r1                      ; SUB SP, SP, #4 | SW R1, SP, #0
    push r2
    pop r3                       ; LW R3, SP, #0 | ADD SP, SP, #4
    pop r4
    
    ; Register-indirect branch (R-Branch format)
    mov r25, lr                  ; MOV expands to ADD R25, LR, #0
    br r25                       ; R-Branch: Target in Rs1 [22:18], Unused [17:0] = 0

; ==============================================================================
; 6. COMPLEX PSEUDO-OPS (CONDITIONAL MATH)
; ==============================================================================
    abs r26, r5                  ; Expands to MOV, CMP, BGE, NEG
    seq r27, r1, r2              ; Set if Equal (Expands to CMP, MOV, BNE, MOV)

; ==============================================================================
; 7. INFINITE LOOP & FUNCTION DEFINITION
; ==============================================================================
end_loop:
    ; EDGE CASE: Branching to self. 
    ; Depending on your hardware's PC logic, offset should be exactly 0 or -1.
    jmp end_loop                   

my_func:
    add r1, r1, #1
    ret                          ; Expands to BR LR