; =========================================================
; SAM32 Assembler "Gauntlet" Stress Test
; 
; This program tests the two-pass layout, label resolution, 
; and complex pseudo-instruction expansion.
; =========================================================
; NOTE: GENERATED BY GPT

.equ MAGIC, 0xDEADBEEF
.equ SIZE, 5

; --- Data Section ---
; The assembler will move this to the end of the binary in Pass 2.
; Because the program is small, these addresses will remain < 4096, 
; fitting perfectly into 13-bit I-Type immediates!
.data
array:      .word 10, -25, 42, 0, 100
result:     .space 20         ; 5 words (20 bytes)

; --- Text Section ---
.text
main:
    ; 1. MULTI-CHUNK LI (32-bit constant)
    ; 0xDEADBEEF requires 3 chunks of 12 bits.
    LI R1, MAGIC              
    
    ; 2. I-TYPE B (NON-COMMUTATIVE IMMEDIATE)
    ; Extract lower 12 bits of MAGIC (0xBEEF & 0xFFF = 0xEEF = 3823)
    AND R2, R1, #0xFFF        
    
    ; R3 = 1000 - 3823 = -2823. Tests the Imm Rs1 toggle!
    SUB R3, #1000, R2         
    
    ; 3. INLINE BARREL SHIFTER & FREEZE FLAG (.F)
    ; Set flags based on R3 (Negative, so N=1, Z=0)
    CMP R3, R0                
    
    ; R4 = R2 + (R2 << 2) = R2 * 5. 
    ; The .F flag prevents this ADD from overwriting the N=1 flag!
    ADD.F R4, R2, R2, LSL #2  
    
    ; Branch if Minus (N=1). Because of .F, N is still 1, so this MUST jump.
    BMI R0, flags_worked          
    
    ; Fail state: trap CPU
    JMP end_test              

flags_worked:
    ; 4. ABSOLUTE ADDRESS LOADING VIA LABEL
    ; The assembler resolves 'array' to its absolute address 
    ; in Pass 2 and encodes it into the 13-bit Imm field.
    ADD R5, R0, array         ; R5 = &array
    ADD R6, R0, result        ; R6 = &result
    
    ; 5. FUNCTION CALL & PUSHM/POPM
    CALL process_array        ; Jumps to function, saves PC to R30 (LR)
    
    ; 6. CONDITIONAL MATH PSEUDO-OPS
    LW R7, R5, #0             ; Load array[0] (10)
    LW R8, R5, #4             ; Load array[1] (-25)
    
    ; SEQ: Set if Equal. R9 = (10 == -25) ? 1 : 0 -> R9 should be 0
    SEQ R9, R7, R8            
    
    ; ABS: Absolute Value. R10 = abs(-25) = 25
    ABS R10, R8                
    
end_test:
    JMP end_test              ; Infinite loop trap

; =========================================================
; Function: process_array
; Iterates through 'array', computes absolute values using 
; hardware branches and I-Type B NEG, and stores them in 'result'.
; =========================================================
process_array:
    PUSHM R5, R6, R7          ; Save registers (Tests multi-line macro)
    
    LI R1, 0                  ; i = 0
    ADD R2, R0, array         ; src_ptr = &array
    ADD R3, R0, result        ; dst_ptr = &result
    
loop_start:
    LW R4, R2, #0             ; Load array[i]
    
    ; Inline absolute value using hardware branch and NEG
    CMP R4, R0                ; Compare with 0
    BGE r0, skip_neg              ; If >= 0, skip negation
    NEG R4, R4                ; R4 = 0 - R4 (Tests I-Type B again!)
    
skip_neg:
    SW R4, R3, #0             ; Store to result[i]
    
    INC R1                    ; i++
    ADD R2, R2, #4            ; src_ptr += 4
    ADD R3, R3, #4            ; dst_ptr += 4
    
    ; Check if i < SIZE (5)
    LI R7, SIZE               ; Load 5 into R7
    CMP R1, R7                ; Compare i with 5
    BLT r0, loop_start            ; Loop if i < 5 (Tests backward PC-relative branch)
    
    POPM R5, R6, R7           ; Restore registers
    RET                       ; Return to main (Expands to BR R30)